from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

btnStud = InlineKeyboardButton(text="Студент", callback_data="stud")
btnEntr = InlineKeyboardButton(text="Абитуриент", callback_data="entr")
btnEmpl = InlineKeyboardButton(text="Сотрудник", callback_data="empl")
#btnGrad = InlineKeyboardButton(text="Послевуз", callback_data="grad")
btnAlum = InlineKeyboardButton(text="Выпускник\nAlumni club", callback_data="alum")
btnInfo = InlineKeyboardButton(text="Контакты", callback_data="info")
btnSocial = InlineKeyboardButton(text="Социальные сети", callback_data="social")
#btnAppl = InlineKeyboardButton(text="Заявка в ДИТ", callback_data="appl")
#btnQans = InlineKeyboardButton(text="Вопрос ответ", callback_data="qans")
BotMenu = InlineKeyboardMarkup(row_width=1)
BotMenu.insert(btnStud)
BotMenu.insert(btnEntr)
BotMenu.insert(btnEmpl)
#BotMenu.insert(btnGrad)
BotMenu.insert(btnAlum)
BotMenu.insert(btnInfo)
BotMenu.insert(btnSocial)
#BotMenu.insert(btnAppl)
#BotMenu.insert(btnQans)

#кнопка назад в меню
btnBack = InlineKeyboardButton(text="Обратно в меню", callback_data="back")
BackMenu = InlineKeyboardMarkup(row_width=1)
BackMenu.insert(btnBack)

#кнопки назад
btnBentr = InlineKeyboardButton(text="Назад", callback_data="bentr")
btnBalum = InlineKeyboardButton(text="Назад", callback_data="balum")
BalumMenu = InlineKeyboardMarkup(row_width=1)
BalumMenu.insert(btnBalum)
BalumMenu.insert(btnBack)

btnBbac = InlineKeyboardButton(text="Назад", callback_data="bbac")
BbacMenu = InlineKeyboardMarkup(row_width=1)
BbacMenu.insert(btnBbac)
BbacMenu.insert(btnBack)
btnBbacFAQ = InlineKeyboardButton(text="Назад", callback_data="bbacfaq")
BbacFAQMenu = InlineKeyboardMarkup(row_width=1)
BbacFAQMenu.insert(btnBbacFAQ)
BbacFAQMenu.insert(btnBack)

btnBmag = InlineKeyboardButton(text="Назад", callback_data="bmag")
BmagMenu = InlineKeyboardMarkup(row_width=1)
BmagMenu.insert(btnBmag)
BmagMenu.insert(btnBack)
btnBdoc = InlineKeyboardButton(text="Назад", callback_data="bdoc")
BdocMenu = InlineKeyboardMarkup(row_width=1)
BdocMenu.insert(btnBdoc)
BdocMenu.insert(btnBack)
btnBcoll = InlineKeyboardButton(text="Назад", callback_data="bcoll")
BcollMenu = InlineKeyboardMarkup(row_width=1)
BcollMenu.insert(btnBcoll)
BcollMenu.insert(btnBack)
btnBUNT = InlineKeyboardButton(text="Назад", callback_data="bUNT")
BUNTMenu = InlineKeyboardMarkup(row_width=1)
BUNTMenu.insert(btnBUNT)
BUNTMenu.insert(btnBack)

btnBstud = InlineKeyboardButton(text="Назад", callback_data="bstud")
BstudMenu = InlineKeyboardMarkup(row_width=1)
BstudMenu.insert(btnBstud)
BstudMenu.insert(btnBack)
btnBstudFAQ = InlineKeyboardButton(text="Назад", callback_data="bstudfaq")
BstudFAQMenu = InlineKeyboardMarkup(row_width=1)
BstudFAQMenu.insert(btnBstudFAQ)
BstudFAQMenu.insert(btnBack)
btnBstudInst = InlineKeyboardButton(text="Назад", callback_data="bstudinst")
BstudInstMenu = InlineKeyboardMarkup(row_width=1)
BstudInstMenu.insert(btnBstudInst)
BstudInstMenu.insert(btnBack)

#меню для абитуриентов
btnBac = InlineKeyboardButton(text="Бакалавриат", callback_data="bac")
btnMag = InlineKeyboardButton(text="Магистратура", callback_data="mag")
btnDoc = InlineKeyboardButton(text="Докторантура", callback_data="doc")
btnColl = InlineKeyboardButton(text="Колледж", callback_data="coll")
btnUNT = InlineKeyboardButton(text="Курсы ЕНТ", callback_data="UNT")
EntrMenu = InlineKeyboardMarkup(row_width=1)
EntrMenu.insert(btnBac)
EntrMenu.insert(btnMag)
EntrMenu.insert(btnDoc)
EntrMenu.insert(btnColl)
EntrMenu.insert(btnUNT)
EntrMenu.insert(btnBack)

#меню для выпускников
btnFAQ = InlineKeyboardButton(text="FAQ", callback_data="faq")
btnClub = InlineKeyboardButton(text="Хочу в клуб!", callback_data="club")
AlumMenu = InlineKeyboardMarkup(row_width=2)
AlumMenu.insert(btnFAQ)
AlumMenu.insert(btnClub)
AlumMenu.insert(btnBack)

#кнопки да/нет для alumni club
btnYesAlum = InlineKeyboardButton(text="Да", callback_data="yalum")
btnNoAlum = InlineKeyboardButton(text="Нет", callback_data="nalum")
YNAlumMenu= InlineKeyboardMarkup(row_width=1)
YNAlumMenu.insert(btnYesAlum)
YNAlumMenu.insert(btnNoAlum)
YNAlumMenu.insert(btnBalum)
YNAlumMenu.insert(btnBack)

#меню для бакалавриата
btnBac1 = InlineKeyboardButton(text="Образовательные программы", callback_data="bac1")
btnBac2 = InlineKeyboardButton(text="Правила приема", callback_data="bac2")
btnBac3 = InlineKeyboardButton(text="Гранты и стипендии", callback_data="bac3")
btnBac4 = InlineKeyboardButton(text="Подача документов", callback_data="bac4")
btnBac5 = InlineKeyboardButton(text="Информация для иногородних и иностранных поступающим", callback_data="bac5")
btnBac6 = InlineKeyboardButton(text="Стоимость обучения", callback_data="bac6")
btnBac7 = InlineKeyboardButton(text="Вопрос-ответ", callback_data="bac7")
BacMenu = InlineKeyboardMarkup(row_width=1)
BacMenu.insert(btnBac1)
BacMenu.insert(btnBac2)
BacMenu.insert(btnBac3)
BacMenu.insert(btnBac4)
BacMenu.insert(btnBac5)
BacMenu.insert(btnBac6)
BacMenu.insert(btnBac7)
BacMenu.insert(btnBentr)
BacMenu.insert(btnBack)

#меню вопросов для бакалавриата
btnBacFAQ1 = InlineKeyboardButton(text="Стоимость 1 кредита в дополнительном семестре?", callback_data="bacfaq1")
btnBacFAQ2 = InlineKeyboardButton(text="Сколько кредитов разрешается брать дополнительном семестре?", callback_data="bacfaq2")
btnBacFAQ3 = InlineKeyboardButton(text="С каким GPA можно перейти с курса на курс?", callback_data="bacfaq3")
btnBacFAQ4 = InlineKeyboardButton(text="У меня есть академическая и финансовая задолженность. Отчислят ли меня из ВУЗа?", callback_data="bacfaq4")
BacFAQMenu = InlineKeyboardMarkup(row_width=1)
BacFAQMenu.insert(btnBacFAQ1)
BacFAQMenu.insert(btnBacFAQ2)
BacFAQMenu.insert(btnBacFAQ3)
BacFAQMenu.insert(btnBacFAQ4)
BacFAQMenu.insert(btnBbac)
BacFAQMenu.insert(btnBack)

#меню для магистратуры
btnMag1 = InlineKeyboardButton(text="Как регистрироваться на КТ", callback_data="mag1")
btnMag2 = InlineKeyboardButton(text="Образовательные программы", callback_data="mag2")
btnMag3 = InlineKeyboardButton(text="КТ для поступления", callback_data="mag3")
btnMag4 = InlineKeyboardButton(text="Стоимость обучения", callback_data="mag4")
btnMag5 = InlineKeyboardButton(text="Подача документов", callback_data="mag5")
btnMag6 = InlineKeyboardButton(text="Международные сертификаты", callback_data="mag6")
btnMag7 = InlineKeyboardButton(text="КЭД", callback_data="mag7")
MagMenu = InlineKeyboardMarkup(row_width=1)
MagMenu.insert(btnMag1)
MagMenu.insert(btnMag2)
MagMenu.insert(btnMag3)
MagMenu.insert(btnMag4)
MagMenu.insert(btnMag5)
MagMenu.insert(btnMag6)
MagMenu.insert(btnMag7)
MagMenu.insert(btnBentr)
MagMenu.insert(btnBack)

#меню вопросов для магистратуры


#меню для докторантуры
btnDoc1 = InlineKeyboardButton(text="Образовательные программы", callback_data="doc1")
btnDoc2 = InlineKeyboardButton(text="Что нужно знать", callback_data="doc2")
btnDoc3 = InlineKeyboardButton(text="Подача документов", callback_data="doc3")
btnDoc4 = InlineKeyboardButton(text="Вопросы прошлых лет", callback_data="doc4")
DocMenu = InlineKeyboardMarkup(row_width=1)
DocMenu.insert(btnDoc1)
DocMenu.insert(btnDoc2)
DocMenu.insert(btnDoc3)
DocMenu.insert(btnDoc4)
DocMenu.insert(btnBentr)
DocMenu.insert(btnBack)

#меню вопросов для докторантуры

#меню для колледжа
btnColl1 = InlineKeyboardButton(text="Контакты и сайт", callback_data="coll1")
btnColl2 = InlineKeyboardButton(text="Правила приема", callback_data="coll2")
CollMenu = InlineKeyboardMarkup(row_width=1)
CollMenu.insert(btnColl1)
CollMenu.insert(btnColl2)
CollMenu.insert(btnBentr)
CollMenu.insert(btnBack)

#меню для ЕНТ
btnUNT1 = InlineKeyboardButton(text="Информация и контакты", callback_data="unt1")
UNTMenu = InlineKeyboardMarkup(row_width=1)
UNTMenu.insert(btnUNT1)
UNTMenu.insert(btnBentr)
UNTMenu.insert(btnBack)

#меню для студентов
btnStud1 = InlineKeyboardButton(text="Platonus", url='https://edu2.aues.kz/')
btnStud2 = InlineKeyboardButton(text="Корпоративная почта", url='https://www.google.com/intl/ru/gmail/about/')
btnStud3 = InlineKeyboardButton(text="Контакты", callback_data="stud3")
btnStud4 = InlineKeyboardButton(text="ЦАК", callback_data="stud4")
btnStud5 = InlineKeyboardButton(text="Блог ректора", url='https://aues.edu.kz/ru/site/blog-rektora')
btnStud6 = InlineKeyboardButton(text="Сброс пароля", url='https://recovery.aues.kz/new-sbros.php')
btnStud7 = InlineKeyboardButton(text="Бухгалтерия", callback_data="stud7")
btnStud8 = InlineKeyboardButton(text="Вопрос-ответ", callback_data="stud8")
StudMenu = InlineKeyboardMarkup(row_width=1)
StudMenu.insert(btnStud1)
StudMenu.insert(btnStud2)
StudMenu.insert(btnStud3)
StudMenu.insert(btnStud4)
StudMenu.insert(btnStud5)
StudMenu.insert(btnStud6)
StudMenu.insert(btnStud7)
StudMenu.insert(btnStud8)
StudMenu.insert(btnBack)

#меню вопросов для студентов
btnStudFAQ1 = InlineKeyboardButton(text="Необходима справка для пособия в ЦОН по потери кормильца. Как ее получить?", callback_data="studfaq1")
btnStudFAQ2 = InlineKeyboardButton(text="Необходима справка для пособия в ЦОН по многодетной семьи. Как ее получить?", callback_data="studfaq2")
btnStudFAQ3 = InlineKeyboardButton(text="Необходима справка для военкомата – как ее получить?", callback_data="studfaq3")
btnStudFAQ4 = InlineKeyboardButton(text="Какие документы мне нужны предоставить при оформлении академического отпуска?", callback_data="studfaq4")
btnStudFAQ5 = InlineKeyboardButton(text="По каким причинам меня могут отчислить из АУЭС?", callback_data="studfaq5")
StudFAQMenu = InlineKeyboardMarkup(row_width=1)
StudFAQMenu.insert(btnStudFAQ1)
StudFAQMenu.insert(btnStudFAQ2)
StudFAQMenu.insert(btnStudFAQ3)
StudFAQMenu.insert(btnStudFAQ4)
StudFAQMenu.insert(btnStudFAQ5)
StudFAQMenu.insert(btnBstud)
StudFAQMenu.insert(btnBack)

#меню институтов для студентов
btnInst1 = InlineKeyboardButton(text="Институт естественных и гуманитарных наук", callback_data="inst1")
btnInst2 = InlineKeyboardButton(text="Институт Автоматизации и информационных технологий", callback_data="inst2")
btnInst3 = InlineKeyboardButton(text="Институт Коммуникационной и космической инженерии", callback_data="inst3")
btnInst4 = InlineKeyboardButton(text="Институт энергетикии зеленых технологий", callback_data="inst4")
InstMenu = InlineKeyboardMarkup(row_width=1)
InstMenu.insert(btnInst1)
InstMenu.insert(btnInst2)
InstMenu.insert(btnInst3)
InstMenu.insert(btnInst4)
InstMenu.insert(btnBstud)
InstMenu.insert(btnBack)