from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

btnInfo = InlineKeyboardButton(text="Контакты", callback_data="info")
btnBac = InlineKeyboardButton(text="Бакалавриат", callback_data="bac")
btnMag = InlineKeyboardButton(text="Магистратура", callback_data="mag")
BotMenu = InlineKeyboardMarkup(row_width=3)
BotMenu.insert(btnInfo)
BotMenu.insert(btnBac)
BotMenu.insert(btnMag)

btnBack = InlineKeyboardButton(text="Назад", callback_data="back")
BackMenu = InlineKeyboardMarkup(row_width=1)
BackMenu.insert(btnBack)

btnBac1 = InlineKeyboardButton(text="Вычислительная техника и программное обеспечение", callback_data="bac1")
btnBac2 = InlineKeyboardButton(text="Автоматизация и управление", callback_data="bac2")
btnBac3 = InlineKeyboardButton(text="Космическая техника и технологии", callback_data="bac3")
btnBac4 = InlineKeyboardButton(text="Радиотехника, электроника и телекоммуникации", callback_data="bac4")
btnBac5 = InlineKeyboardButton(text="Энергетика", callback_data="bac5")
BacMenu = InlineKeyboardMarkup(row_width=1)
BacMenu.insert(btnBac1)
BacMenu.insert(btnBac2)
BacMenu.insert(btnBac3)
BacMenu.insert(btnBac4)
BacMenu.insert(btnBac5)
BacMenu.insert(btnBack)

btnMag1 = InlineKeyboardButton(text="Информатика", callback_data="mag1")
btnMag2 = InlineKeyboardButton(text="Информационные системы", callback_data="mag2")
btnMag3 = InlineKeyboardButton(text="Вычислительная техника и программное обеспечение", callback_data="mag3")
btnMag4 = InlineKeyboardButton(text="Радиотехника, электроника и телекоммуникации (научно-педагогическая магистратура)", callback_data="mag4")
btnMag5 = InlineKeyboardButton(text="Радиотехника, электроника и телекоммуникации (профильная магистратура)", callback_data="mag5")
MagMenu = InlineKeyboardMarkup(row_width=1)
MagMenu.insert(btnMag1)
MagMenu.insert(btnMag2)
MagMenu.insert(btnMag3)
MagMenu.insert(btnMag4)
MagMenu.insert(btnMag5)
MagMenu.insert(btnBack)